config/routes.rb
PlayTheCall::Application.routes.draw do
  devise_for :users,
             controllers: { omniauth_callbacks: "users/omniauth_callbacks",
                            :registrations => :registrations}

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  get 'm/:nickname/:slug' => 'mission_enrollments#show',  as: 'mission_enrollment'
  get 'ranking'           => 'ranking#show',              as: 'ranking'
  get 'cities/by_country' => 'cities#by_country'

  match 'countdown' => 'welcome#countdown', as: 'countdown'

  resources :users

  resources :pages, except: [:show]

  match '/pages/:slug', :to => 'pages#show', as: 'page'

  match '/missions/end_of_chapter', :to => 'missions#end_of_chapter', as: 'end_of_chapter'

  resources :missions, only: :show do
    member do
      get 'welcome'
      get 'congratulations'
    end
    resources :mission_enrollments, except: [:destroy, :index, :show] do
      resources :status_updates, except: [:index, :show]
      member do
        post 'check'
        get 'check'
        get 'badge'
      end
    end
  end

  root to: 'welcome#index'
end

app/models/user.rb
class User < ActiveRecord::Base

  ELEMENTS = ['earth', 'fire', 'air', 'water', '']
  USERS_COUNT_LIMIT = 3000

  has_one    :profile
  has_many   :mission_enrollments
  has_many   :missions, through: :chapter
  has_many   :chapters, through: :game_version
  belongs_to :city
  belongs_to :game_version
  belongs_to :oracle

  attr_accessor :country_id

  accepts_nested_attributes_for :profile, :oracle

  validates_presence_of   :city
  validates_presence_of   :game_version

  validates_format_of     :nickname, :with => /^[a-z_\-0-9]+$/
  validates_uniqueness_of :nickname

  validates_inclusion_of :gender,  in: ['male', 'female']
  validates_inclusion_of :element, in: ELEMENTS

  validates_presence_of :birthday
  validate :validate_birthday

  mount_uploader :avatar, UsersAvatarUploader

  attr_accessible :city_id, :email,  :password, :password_confirmation, :avatar,
                  :avatar_cache, :remember_me, :provider, :element, :uid,
                  :points, :game_version_id, :nickname, :gender, :name,
                  :profile, :avatar_cache, :profile_attributes, :bio, :city_id,
                  :oracle_attributes, :country_id, :facebook_profile, :twitter_profile,
                  :google_plus_profile, :youtube_profile, :instagram_profile, :birthday

  devise :database_authenticatable,   :trackable,
         :recoverable, :rememberable, :confirmable,
         :validatable, :omniauthable, :registerable

  def self.limit_exceeded?
    count >= USERS_COUNT_LIMIT
  end

  def last_mission_enrollment
    mission_enrollments.order('created_at DESC').limit(1).first
  end

  def self.ranking
    User.where('points > ?', 0).order('points DESC').limit(10)
  end

  def has_accomplished?(mission)
    mission_enrollments.any? {|m| m.mission == mission and m.accomplished }
  end

  def nickname=(value)
    self[:nickname] = value.downcase
  end

  def current_chapter
    chapters.order("position ASC").select { |c| !Chapter.finished?(c, self) }.first or
      chapters.order("position ASC").first
  end

  def current_mission
    if mission_enrollments.any?
      finished_mission_ids   = mission_enrollments.where(accomplished: true).pluck :mission_id
      unfinished_mission_ids = mission_enrollments.where(accomplished: false).pluck :mission_id
      current_chapter.missions.where(id: unfinished_mission_ids).order("position ASC").first or
        current_chapter.missions.where("id not in (#{finished_mission_ids.join(",")})").order("position ASC").first
    else
      current_chapter.missions.order("position ASC").first
    end
  end

  def current_mission_enrollment
    mission_enrollments.find_by_mission_id(current_mission.try(:id))
  end

  # If current user is OK with all mission enrollments
  def accomplished_all_enrolled_missions?
    mission_enrollments.select{|m| !m.accomplished? }.empty?
  end

  # Returns the last +MissionEnrollment+
  def last_accomplished_mission_enrollment
    mission_enrollments.accomplished.last
  end

  def current_or_last_accomplished_mission_enrollment
    return last_accomplished_mission_enrollment if accomplished_all_enrolled_missions?
    current_mission_enrollment
  end

  def aggregate_points!
    update_attribute(:points, aggregate_points)
  end

  def aggregate_points
    mission_enrollments.map{|me| me.validator.enrollment_params[:likes]}.
                        reduce(0, :+)
  end

  # If user can enroll the next mission
  def can_enroll?(mission)
    (mission_enrollments.empty? && (mission == current_chapter.missions.first_mission)) ||
    ( (current_or_last_accomplished_mission_enrollment && current_or_last_accomplished_mission_enrollment.accomplished?) &&
    (last_accomplished_mission_enrollment.mission.next_mission == mission ) )
  end

  private

  def validate_birthday
    birthday = read_attribute(:birthday)
    if birthday && birthday > 13.years.ago.to_date
      errors.add :birthday, I18n.t('activerecord.user.invalid_birthday_message')
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
     redirect_to 'users/sign_up'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include ApplicationHelper

  before_filter :authenticate_user!
  before_filter :check_users
  before_filter :load_user_country
  before_filter :load_countries
  before_filter :load_cities

  def edit
  end

  def update
    params[:user].delete :nickname
    if @user.update_attributes params[:user]
      redirect_to user_current_mission
    else
      render :edit
    end
  end

  private

  def check_users
    @user = User.find params[:id]
    redirect_to :root unless current_user == @user
  end

  def load_user_country
    @country = @user.city.country
  end

  def load_cities
    @cities = City.where(:country_id => @country.id)
  end
end

app/views/users/_form.html.erb
<% if @user.new_record? %>
  <%= f.label :nickname %>
  <%= f.text_field :nickname %>
<% end %>

<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :email %>
<%= f.email_field :email %>

<%= f.label :birthday %>
<%= f.date_select :birthday, :start_year => 1920, :end_year => Time.now.year %>

<%= field_set_tag do %>
  <h1><%= t('registration.social_network') %></h1>
  <%= f.label :facebook_profile %>
  <%= f.text_field :facebook_profile %>
  <%= f.label :twitter_profile %>
  <%= f.text_field :twitter_profile %>
  <%= f.label :google_plus_profile %>
  <%= f.text_field :google_plus_profile %>
  <%= f.label :youtube_profile %>
  <%= f.text_field :youtube_profile %>
  <%= f.label :instagram_profile %>
  <%= f.text_field :instagram_profile %>
<% end %>

<%= f.label :country %>
<%= f.collection_select :country_id, @countries, :id, :name, {:prompt => t('registration.select_country'), :selected => @country.try(:id)}, :class => 'chzn-select'  %>

<%= f.label :city %>
<%= f.collection_select :city_id, @cities, :id, :name, {}, :class => 'chzn-select' %>

<%= f.label :game_version %>
<%= f.collection_select :game_version_id, GameVersion.all, :id, :name, {}, :class => 'chzn-select' %>

<%= f.label :avatar %>
<%= f.file_field :avatar %>
<%= f.hidden_field :avatar_cache %>

<%= f.label :gender %>
<p>
  <%= f.radio_button :gender, 'male' %>
  <%= label :user_gender, :male %>
  <%= f.radio_button :gender, 'female' %>
  <%= label :user_gender, :female %>
</p>

<%= f.fields_for :profile do |profile_form| %>
  <%= profile_form.label :bio %>
  <%= profile_form.text_area :bio, rows: 5 %>
<%end%>

<% if f.object.new_record? %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

<% else %>

  <%= link_to t('actions.change_password'), edit_user_registration_path, :class => 'cancel_account' %>

<% end %>

<p class="buttons">
  <%= link_to t("actions.cancel"), root_path, class: :cancel %>
  <%= f.submit t("actions.save") %>
</p>

app/views/users/_sidebar.html.erb
<aside>
  <section class="profile">
    <%= image_tag avatar_url, class: :avatar %>
    <h1><%= current_user.name %></h1>
    <strong><%= current_user.city.name %> <span><%= current_user.city.country.name %></span></strong>
    <p class="bio">
      <%= current_user.profile.bio %>
    </p>
    <%= render "users/social" %>
    <a href="" class="more" data-text="<%= t("actions.see_less") %>"><%= t("actions.see_more") %></a>
  </section>
  <section class="points">
    <div class="total-points">
      <%= t("sidebar.user_points", points: current_user.points) %>
    </div>
    <div class="badges">
      <ul>
        <% badge_for_user(current_user).each do |badge| %>
          <li><%= image_tag badge.image.small %></li>
        <% end %>
      </ul>
    </div>
    <%= link_to t("ranking.translation"), ranking_path, class: 'btn btn-ranking' %>
  </section>
  <section class="missions">
    <h1><%= t("mission.pluralized") %></h1>
    <ul>
      <% current_user.current_chapter.missions.order("position ASC").each do |mission| %>
        <% if current_user.has_accomplished?(mission) || current_user.current_mission == mission %>
          <li><%= link_to t("actions.mission_link", position: mission.position, title: mission.title),
            mission_path(mission) %></li>
        <% else %>
          <li><%= mission.position %> <span><%= mission.title %></span></li>
        <% end %>
      <% end %>
    </ul>
  </section>
</aside>

app/views/users/_social.html.erb
<ul class="social">
  <% if current_user.facebook_profile? %>
    <li class="facebook"><%= link_to "Facebook", current_user.facebook_profile, title: "Facebook", target: "_blank" %></li>
  <% end %>
  <% if current_user.twitter_profile? %>
    <li class="twitter"><%= link_to "Twitter", current_user.twitter_profile, title: "Twitter", target: "_blank" %></li>
  <% end %>
  <% if current_user.google_plus_profile? %>
    <li class="google_plus"><%= link_to "G+", current_user.google_plus_profile, title: "Google Plus", target: "_blank" %></li>
  <% end %>
  <% if current_user.youtube_profile? %>
    <li class="youtube"><%= link_to "Youtube", current_user.youtube_profile, title: "Youtube", target: "_blank" %></li>
  <% end %>
  <% if current_user.instagram_profile? %>
    <li class="instagram"><%= link_to "Instagram", current_user.instagram_profile, title: "Instagram", target: "_blank" %></li>
  <% end %>
</ul>

app/views/users/edit.html.erb
<%= form_for(@user, html: {multipart: true}) do |f| %>
  <h2><%= t("actions.edit_profile") %></h2>

  <%= render partial: 'form', locals: {f: f} %>
<% end %>