config/routes.rb
PlayTheCall::Application.routes.draw do
  devise_for :users,
             controllers: { omniauth_callbacks: "users/omniauth_callbacks",
                            :registrations => :registrations}

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  get 'm/:nickname/:slug' => 'mission_enrollments#show',  as: 'mission_enrollment'
  get 'ranking'           => 'ranking#show',              as: 'ranking'
  get 'cities/by_country' => 'cities#by_country'

  match 'countdown' => 'welcome#countdown', as: 'countdown'

  resources :users

  resources :pages, except: [:show]

  match '/pages/:slug', :to => 'pages#show', as: 'page'

  match '/missions/end_of_chapter', :to => 'missions#end_of_chapter', as: 'end_of_chapter'

  resources :missions, only: :show do
    member do
      get 'welcome'
      get 'congratulations'
    end
    resources :mission_enrollments, except: [:destroy, :index, :show] do
      resources :status_updates, except: [:index, :show]
      member do
        post 'check'
        get 'check'
        get 'badge'
      end
    end
  end

  root to: 'welcome#index'
end

app/views/shared/_footer.html.erb
<footer>
  <div class="content">
    <ul>
      <li><%= link_to t("home.footer.about"), page_path(t("pages.about")) %></li>
      <li><%= link_to t("home.footer.how_to"), page_path(t("pages.how_to")) %></li>
      <li><%= link_to t("home.footer.terms"), page_path(t("pages.terms")) %></li>
      <li><%= link_to t("home.footer.principles"), page_path(t("pages.principles")) %></li>
      <% if params[:controller] == 'welcome' && params[:action] == 'index' %>
        <li><%= st("home.footer.creative_commons") %></li>
      <% end %>
    </ul>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <section class="content-header">
    <h1><%= link_to "Play the Call", root_path %></h1>
    <ul class="menu">
      <% if user_signed_in? %>
        <% if current_user.mission_enrollments.any? %>
          <li>
            <%= link_to t('actions.my_missions'), mission_enrollment_path(current_user.nickname, last_available_mission_enrollment.mission.slug) %>
          </li>
        <% end %>
        <li class="settings">
          <%= link_to t('actions.config'), edit_user_path(current_user) %>
          <ul class="settings-drop">
            <li><%= link_to t('actions.edit_profile'), edit_user_path(current_user) %></li>
            <li><%= link_to t('actions.sign_out'), destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
      <% else %>
        <li>
          <%= link_to t('actions.sign_in'), new_user_session_path %>
        </li>
        <li>
          <%= link_to t('actions.fancy_sign_up'), new_user_registration_path, class: 'sign-in' %>
        </li>
      <% end %>
    </ul>
  </section>
</header>