config/routes.rb
PlayTheCall::Application.routes.draw do
  devise_for :users,
             controllers: { omniauth_callbacks: "users/omniauth_callbacks",
                            :registrations => :registrations}

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  get 'm/:nickname/:slug' => 'mission_enrollments#show',  as: 'mission_enrollment'
  get 'ranking'           => 'ranking#show',              as: 'ranking'
  get 'cities/by_country' => 'cities#by_country'

  match 'countdown' => 'welcome#countdown', as: 'countdown'

  resources :users

  resources :pages, except: [:show]

  match '/pages/:slug', :to => 'pages#show', as: 'page'

  match '/missions/end_of_chapter', :to => 'missions#end_of_chapter', as: 'end_of_chapter'

  resources :missions, only: :show do
    member do
      get 'welcome'
      get 'congratulations'
    end
    resources :mission_enrollments, except: [:destroy, :index, :show] do
      resources :status_updates, except: [:index, :show]
      member do
        post 'check'
        get 'check'
        get 'badge'
      end
    end
  end

  root to: 'welcome#index'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout 'welcome'
  before_filter :mission_redirect

  def index
    # selects one user per city
    @users = User.includes(:city).select('DISTINCT ON (city_id) city_id, users.*')
  end

  private

  def mission_redirect
    if user_signed_in?
      if current_user.current_mission.present?
        redirect_to user_current_mission
      elsif Chapter.finished?(current_user.current_chapter, current_user)
        redirect_to end_of_chapter_path
      end
    end
  end
end

app/views/welcome/_intro_modal.html.erb
<div id="intro" class="reveal-modal">
	<%= image_tag 'home/logo.png', class: :logo, size: '520x170' %>
	<h1><%= t("home.heading") %></h1>
	<iframe id="youtube" width="520" height="275" src="http://www.youtube.com/embed/3_5St3mS8Kw" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
	<%= link_to t("actions.skip"), new_user_registration_path, class: "btn close-reveal-modal" %>
</div>

app/views/welcome/_sign_in.html.erb
<div id="sign_in" class="reveal-modal">
	<%= image_tag 'home/logo.png', class: :logo, size: '520x170' %>
  <div class="login">
    <%= form_for "user", :url => user_session_path do |f| %>
      <ul>
        <li>
          <%= f.label :email %>
          <%= f.email_field :email %>
        </li>
        <li>
          <%= f.label :password %>
          <%= f.password_field :password %>
        </li>
      </ul>
      <%= link_to t("actions.forgot_password"), new_password_path('user'), class: 'forgot' %>
      <%= f.submit t("actions.sign_in") %>
    <% end %>
  </div>
</div>

app/views/welcome/countdown.html.erb
<html>
  <head>
    <title></title>
    <style type="text/css">
      body {
        padding:0;
        margin: 0;
        background: #001320 url('assets/countdown.jpg') repeat-x;
      }
      .content {
        width: 510px;
        margin-left: auto;
        margin-right: auto;
        margin-top: 100px;
      }
      .content .logo {
        width: 500px;
      }

      .content div{
        width: 490px;
        margin: 0 auto;
      }
      .content div img{
        margin: 10px;
      }
      .days {
        margin-left: auto;
        margin-right: auto;
      }

    </style>
  </head>
  <body>
    <div class="content">
      <%= image_tag("home/logo.png", :class => "logo") %>
      <div>
        <%= image_tag("home/title_top_br.png"); %>
        <%= image_tag("days_br/#{@days_to_release}.png", :class => "days"); %>
        <%= image_tag("home/title_bottom_br.png") %>
      </div>
    </div>
  </body>
  <script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-37165625-1']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
  </script>
</html>

app/views/welcome/index.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag 'home/default' %>
  <%= stylesheet_link_tag 'home/reveal' %>
<% end %>

<% content_for :footer do %>
  <script type="text/javascript">
    $(document).ready(function(){
      $("canvas").attr("height", $(window).height());
      $("canvas").attr("width", $(window).width());
    });
  </script>
  <%= javascript_include_tag "home/Tween.js" %>
  <%= javascript_include_tag "home/jquery.mousewheel.js" %>
  <%= javascript_include_tag "home/src_r47/Three.js" %>
  <%= javascript_include_tag "home/jquery.colorbox-min.js" %>
  <%= javascript_include_tag "home/Detector.js" %>
  <%= javascript_include_tag "home/dat.gui.min.js" %>
  <%= javascript_include_tag "home/globe_min.js" %>
  <%= javascript_include_tag "home/jquery.reveal.js" %>
  <script>
    $('div#globeGl_').doGlobe({
      globeRadius: 650,
      backPlateMargin: 10,
      camX: 0,
      camY: -50,
      camZ: 1500,
      cameraTargetX:0,
      cameraTargetY:200,
      cameraTargetZ:0
    });
  </script>
<% end %>
<div class="content">
  <%= image_tag 'home/logo.png', class: :logo %>
  <div class="in">
    <h1><%= t("home.heading") %></h1>
    <p><%= t("home.description") %></p>
    <ul>
      <li><a href="#" data-reveal-id="intro" data-animation="fade" class="sign_up"><%= t("actions.sign_up") %></a></li>
      <li><%= t("home.or") %> <%= link_to t("actions.sign_in"), new_user_session_path, class: "sign_in", :'data-reveal-id' => 'sign_in', :'data-animation' => 'fade' %></li>
    </ul>
  </div>
  <%= render 'shared/footer' %>
</div>
<div id="globeContent">
  <div id="globeGl_" class="globeGl"></div>
</div>

<% @users.each do |user| %>
  <div class="poi hidden" data-lat="<%= user.city.latitude %>" data-long="<%= -user.city.longitude %>" data-url="globe_camPos.html">
    <%= user.city.name %>
  </div>
<% end %>

<%= render 'intro_modal' %>
<%= render 'sign_in' %>