config/routes.rb
PlayTheCall::Application.routes.draw do
  devise_for :users,
             controllers: { omniauth_callbacks: "users/omniauth_callbacks",
                            :registrations => :registrations}

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  get 'm/:nickname/:slug' => 'mission_enrollments#show',  as: 'mission_enrollment'
  get 'ranking'           => 'ranking#show',              as: 'ranking'
  get 'cities/by_country' => 'cities#by_country'

  match 'countdown' => 'welcome#countdown', as: 'countdown'

  resources :users

  resources :pages, except: [:show]

  match '/pages/:slug', :to => 'pages#show', as: 'page'

  match '/missions/end_of_chapter', :to => 'missions#end_of_chapter', as: 'end_of_chapter'

  resources :missions, only: :show do
    member do
      get 'welcome'
      get 'congratulations'
    end
    resources :mission_enrollments, except: [:destroy, :index, :show] do
      resources :status_updates, except: [:index, :show]
      member do
        post 'check'
        get 'check'
        get 'badge'
      end
    end
  end

  root to: 'welcome#index'
end

app/models/mission_enrollment.rb
class MissionEnrollment < ActiveRecord::Base
  has_many :enrollment_images
  has_many :status_updates

  belongs_to :mission
  belongs_to :user

  validates_presence_of :user_id
  accepts_nested_attributes_for :enrollment_images
                                #reject_if: lambda do |attributes|
                                #  attributes['image'].blank?
                                #end

  attr_accessible :title, :description, :user, :mission, :user_id,
                  :enrollment_images_attributes, :mission_id

  before_create :fill_url
  before_save   :compile_description
  before_save   :update_accomplished

  after_initialize :initialize_validation_params

  scope :accomplished, where(accomplished: true)
  scope :unaccomplished, where(accomplished: false)

  delegate :nickname, to: :user, :prefix => true, :allow_nil => true

  def validator
    mission.validator self
  end

  def presenter(view)
    validator.presenter(view)
  end

  def check(params)
    validator.check params
    user.aggregate_points!
  end

  def async_check(params = {})
    MissionCheckJob.check self, params
  end

  def lazy_check(params = {})
    MissionCheckJob.lazy_check self, params
  end

  def create_next
    if mission.next_mission
      mission.next_mission.mission_enrollments.create user: user
    else
      return nil if mission.element == user.element

      next_mission = Mission.first_for user
      if next_mission && !user.mission_enrollments.from_mission(next_mission.id).exists?
        next_mission.mission_enrollments.create user: user
      else
        nil
      end
    end
  end

  def mission_id=(mission_id)
    self[:mission_id] = mission_id
    initialize_validation_params
    mission_id
  end

  protected

  def accomplished_callback
    MissionMailer.accomplished_mission(self, self.user).deliver
  end

  def fill_url
    self.url = "#{ I18n.t 'url' }m/#{user.nickname}/#{mission.slug}"
  end

  def initialize_validation_params
    if mission
      self.validation_params ||= YAML.dump(validator.initialize_params)
    end
  end

  def compile_description
    if description_changed?
      self.html_description = RDiscount.new(description).to_html
    end
    true
  end

  def update_accomplished
    unless accomplished?
      self.accomplished = validator.accomplished?
      accomplished_callback if accomplished?
    end
    true
  end
end

app/controllers/mission_enrollment_controller.rb
class MissionEnrollmentController < ApplicationController
  def check
    @enrollment = MissionEnrollment.find_by_url "m/#{params[:nickname]}/#{params[:slug]}"
    render text: @enrollment.check
  end

  def show
    @enrollment = MissionEnrollment.find_by_url "m/#{params[:nickname]}/#{params[:slug]}"
  end
end

app/controllers/mission_enrollments_controller.rb
class MissionEnrollmentsController < ApplicationController
  prepend_before_filter :authenticate_user!, only: [:new]

  before_filter :load_mission, only: [:new, :edit, :create]
  before_filter :load_mission_enrollments, only: :show

  def new
    if current_user.can_enroll?(@mission)
      @mission_enrollment = @mission.enroll current_user
    else
      redirect_to root_path
    end
  end

  def show
    @mission_enrollment.lazy_check
  end

  def check
    @mission_enrollment = MissionEnrollment.find_by_url "m/#{params[:nickname]}/#{params[:slug]}"
    @mission_enrollment.async_check(params)
    redirect_to mission_enrollment_path nickname: @mission_enrollment.user.nickname,
                                        slug:     @mission_enrollment.mission.slug
  end

  def index
    @user = current_user if user_signed_in?
    @enrollment = MissionEnrollment.find_by_url "m/#{params[:nickname]}/#{params[:slug]}"
  end

  def update
    mission_id = Mission.find_by_slug(params[:mission_id]).id
    mission_enrollment = MissionEnrollment.find_by_mission_id_and_user_id(mission_id, current_user.id)
    mission_enrollment.update_attributes(params[:mission_enrollment])
    mission_enrollment.save
    redirect_to mission_enrollment_path nickname: mission_enrollment.user.nickname,
                                        slug:     mission_enrollment.mission.slug
  end

  def create
    if current_user.can_enroll?(@mission)
      @mission_enrollment = MissionEnrollment.new params[:mission_enrollment]
      if @mission_enrollment.save
          redirect_to mission_enrollment_path nickname: @mission_enrollment.user.nickname,
                                              slug:     @mission_enrollment.mission.slug
      else
        render :new
      end
    else
      redirect_to root_path
    end
  end

  private
  def load_mission_enrollments
    slug = params[:slug]
    @user = User.find_by_nickname params[:nickname]
    @mission_enrollment = @user.mission_enrollments.joins(:mission).
                                where('missions.slug = ?', slug).first
    @enrolled_missions = @user.mission_enrollments.dup
    @enrolled_missions.delete_if { |e| e.id == @mission_enrollment.id }
  end

  def load_mission
    @mission = current_user.current_chapter.missions.find_by_slug params[:mission_id]
  end
end

app/views/mission_enrollments/_enrolled_missions.html.erb
<% if @enrolled_missions.present? %>
  <% @enrolled_missions.each do |enrolled_mission| %>
    <li>
      <h2><%= link_to enrolled_mission.mission.title, mission_enrollment_path(enrolled_mission.user_nickname, enrolled_mission.mission.slug) %></h2>
      <ul class="points-other-mission">
        <% if enrolled_mission.mission.badge.present? %>
          <li><%= image_tag(enrolled_mission.mission.badge.image.small) %></li>
        <% end %>
        <li><h2><%= t("mission.like_count", quantity: validation_params(enrolled_mission)[:likes]) %></h2></li>
        <li><%= image_tag("icons/check.jpg") %></li>
      </ul>
    </li>
  <% end %>
<% end %>

app/views/mission_enrollments/_enrollment_image_fields.html.erb
<div style="margin: 10px 0"><%= f.file_field :image %><div>
<%#= link_to_remove_fields "remove", f %>

app/views/mission_enrollments/_form.html.erb
<section class="content">
  <div class="content-base">
    <h1><%= st 'mission.indexed_title', position: mission.position, title: mission.title %></h1>

    <%= form_for [mission, @mission_enrollment] do |f| %>

      <%= f.fields_for :enrollment_images do |i| %>
        <%= i.label :image %>
        <%= i.file_field :image %>
      <% end %>

      <%= presenter_for_enrollment_form @mission_enrollment, f %>
      <p><%= link_to_add_fields t('actions.add_image'), f, :enrollment_images %></p>

      <%= f.label :description %>
      <%= f.text_area :description, rows: 5 %>

      <%= f.hidden_field :mission_id %>
      <%= f.hidden_field :user_id %>

      <p class="buttons">
        <%= link_to t('actions.cancel'), mission_path(mission) %>
        <%= f.submit button, class: 'btn' %>
      </p>
    <% end %>
  </div>
</section>

<%= javascript_include_tag 'extensions/nested_form' %>

app/views/mission_enrollments/badge.html.erb
hi

app/views/mission_enrollments/edit.html.erb
<%= render "form",  mission: @mission, button: t("actions.update") %>

app/views/mission_enrollments/new.html.erb
<%= render "form",  mission: @mission, button: t("actions.save") %>

app/views/mission_enrollments/show.html.erb
<% content_for :head do %>
  <%= javascript_include_tag "extensions/slides.min.jquery" %>
  <%= stylesheet_link_tag 'slides' %>

  <script type="text/javascript">
    $(function(){
      $('#slides').slides({
        preload: true,
        preloadImage: '/assets/slides/loading.gif',
        play: 5000,
        pause: 2500,
        hoverPause: true,
        pagination: false
      });
    });
  </script>
<% end %>

<section class="content">
  <div class="content-base">
    <div id="slides">
      <div class="slides_container">
        <% @mission_enrollment.enrollment_images.each do |enrollment_image| %>
          <div class="slide">
            <%= image_tag enrollment_image.image.medium %>
          </div>
        <% end %>
      </div>
      <a href="#" class="prev"><img src="/assets/slides/arrow-prev.png" width="24" height="43" alt="Prev"></a>
      <a href="#" class="next"><img src="/assets/slides/arrow-next.png" width="24" height="43" alt="Next"></a>
    </div>
    <h1><%= st 'mission.indexed_title', position: @mission_enrollment.mission.position, title: @mission_enrollment.mission.title %></h1>
    <%= @mission_enrollment.html_description.to_s.html_safe %>

    <% @mission_enrollment.status_updates.order("created_at DESC").each do |status_update| %>
      <h2><%= l status_update.created_at, format: :short %></h2>
      <ul class="actions">
        <li><%= link_to t("actions.edit"), edit_mission_mission_enrollment_status_update_path(@mission_enrollment.mission, @mission_enrollment, status_update) %></li>
        <li><%= link_to t("actions.destroy"), mission_mission_enrollment_status_update_path(@mission_enrollment.mission, @mission_enrollment, status_update), method: :delete, confirm: t("actions.confirm_destroy") %></li>
      </ul>
      <%= status_update.html_status.html_safe %>
    <% end %>
    <% if @mission_enrollment.user_id == current_user.try(:id) %>
      <%= link_to t("actions.update_status"), new_mission_mission_enrollment_status_update_path(@mission_enrollment.mission, @mission_enrollment), class: 'update_status' %>
    <% end %>
    <%= presenter_for_enrollment(@mission_enrollment) %>

    <fb:comments href="<%= @mission_enrollment.url %>" width="660" num_posts="10"></fb:comments>
  </div>
</section>

<ul class="other-missions">
  <%= render "mission_enrollments/enrolled_missions" %>
</ul>